### ISSUE TITLE
after channging db dir, automatically display "stop/start" dialog

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/neoclipse#4]

**Comment by nrkkalyan** [comment]
Do you mean a popup message with start and stop buttons.

**Comment by peterneubauer** [comment]
Yes,
it's kinda not inuitive to not switch to the new db after configuring
it. An alternative to go with a normal "connect" style of config that
other SQL browsers have, that would be even more expected behaviour
(having a "connections" view with the configured DB locations, and
start/stop them.

Something like http://www.sqlexplorer.org/connections.php

WDYT?

On Fri, Dec 16, 2011 at 9:33 AM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
Ya, its nice, I will start working on this today.

**Comment by peterneubauer** [comment]
It's just a suggestion, there might be others that are better. WDYT of an approach like http://wiki.eclipse.org/index.php/Getting_Started_with_DTP?

**Comment by nrkkalyan** [comment]
Hi

I saw this when exploring different plugins, but I felt that SQL Explorer
has more clean UI.
I am attaching a screenshot of the current implementation I started with,
if you like then let me know otherwise I revert all my changes and will
start with DTP.

If you have any further idea in mind about the look and feel of UI then
please let me know I will be happy to work with that.

Kalyan

On Sun, Dec 18, 2011 at 5:39 PM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> It's just a suggestion, there might be others that are better. WDYT of an
> approach like http://wiki.eclipse.org/index.php/Getting_Started_with_DTP?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/4#issuecomment-3195512

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by peterneubauer** [comment]
No,
just go ahead, I think we should keep it easy and clean, was just a thought. I think DTP is a bit too much.
